version: '2.4'
services:

    db:
        image: postgres:10.6
        environment:
            POSTGRES_USER: odoo
            POSTGRES_PASSWORD: odoo
            POSTGRES_DB: postgres
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - db:/var/lib/postgresql/data/pgdata

    redis:
        image: redis:4-alpine
        volumes:
            - redis:/data
        command:
            - redis-server
            - --appendonly
            - 'yes'
        
    odoo:
        image: druidoo/odoo-saas:12.0-enterprise
        ports:
            - "8069:8069"
        
        tty: true
        stdin_open: true

        environment:
            DATABASE: &dbname test
            PGDATABASE: *dbname
            WAIT_PG: 'true'
            LIST_DB: 'true'
            UNACCENT: 'true'
            LOG_LEVEL: 'debug'
            # Odoo-saas
            FIXDBS: 'true'
            SERVER_MODE: Dev
            SERVER_WIDE_MODULES: base,web,server_mode,saas_client
            # Redis session store (only if odoo-saas)
            REDIS_HOST: redis
            ENABLE_REDIS: 'True'
            # Custom Entrypoints
            CUSTOM_CONFIG: |-
                [options]

        volumes:
            - ./repositories:/home/odoo/custom/repositories:rw,z
            - filestore:/home/odoo/data
            - /etc/timezone:/etc/timezone:ro

        depends_on:
            - db
            - redis

volumes:
    db:
    filestore:
    redis:
